version: "3"
services:
  store:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.1
    ports:
    - 9200:9200
    - 9300:9300
    volumes:
    - ./store/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - es_data:/usr/share/elasticsearch/data
    environment:
    - discovery.type=single-node
  api:
    build: ./api
    ports:
    - 3000:3000
    depends_on:
    - store
volumes:
  es_data:
