apiVersion: v1
kind: Pod
metadata:
  name: search
spec:
  containers:
  - name: store
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.1
    ports:
    - containerPort: 9200
    volumeMounts:
    - mountPath: /usr/share/elasticsearch/data
      name: es-data
  - name: api
    image: searchservice_api
    ports:
    - containerPort: 3000
  volumes:
  - name: es-data
    emptyDir: {}