version: "3"
services:
  store:
    image: postgres:alpine
    container_name: db
    environment:
    - POSTGRES_PASSWORD=pg123456
    ports:
    - 5432:5432
    volumes:
    - data:/var/lib/postgresql/data
  api:
    build: ./api
    ports:
    - 3002:3002
    depends_on:
    - store
volumes:
  data: